<h3 align="center" style="color:blue">Codebasics Python Course: Numpy Exercise</h3>

At **AtliQ**, a software service company, the **HR team** wants to understand how happy employees are with company policies and how long they've been with the company. This survey aims to help HR improve the work environment and keep employees satisfied.

**Data Structure:** Two numpy arrays capture survey results and employee details:

**Employee Details:** Contains Employee ID, Department, and Number of Years with AtliQ.

**Survey Results:** Contains Employee ID and Happiness Score (scaled 1-10).

In [1]:
import numpy as np

# Employee Details: Employee ID, Department, Number of Years with AtliQ
employee_details = np.array([
    [101, 'Sales', 3],  
    [102, 'HR', 5],    
    [103, 'IT', 2],        
    [104, 'Sales', 8],    
    [105, 'IT', 6],      
    [106, 'HR', 4],           
    [107, 'IT', 7],    
    [108, 'Sales', 1], 
    [109, 'HR', 3]          
])

# Survey Results: Employee ID, Happiness Score (1-10)
survey_results = np.array([
    [101, 8],
    [102, 10],
    [103, 9],
    [104, 6],
    [105, 7],
    [106, 8],
    [107, 9],
    [108, 5],
    [109, 7]
])


### Task 1: Merge Arrays

**Scenario:** To streamline analysis, combine the employee details with their survey results.

**Action:** Use ```np.hstack``` to horizontally stack the two arrays.

In [2]:
# write code here
employee_details.hstack(survey_results)

AttributeError: 'numpy.ndarray' object has no attribute 'hstack'

In [15]:
merged=np.hstack((employee_details,survey_results))
merged

array([['101', 'Sales', '3', '101', '8'],
       ['102', 'HR', '5', '102', '10'],
       ['103', 'IT', '2', '103', '9'],
       ['104', 'Sales', '8', '104', '6'],
       ['105', 'IT', '6', '105', '7'],
       ['106', 'HR', '4', '106', '8'],
       ['107', 'IT', '7', '107', '9'],
       ['108', 'Sales', '1', '108', '5'],
       ['109', 'HR', '3', '109', '7']], dtype='<U21')

### Task 2: Print Scores

**Scenario:** HR wants a quick view of all happiness scores to gauge overall employee sentiment.

**Action:** Display all happiness scores from the merged array.

In [6]:
# write code here
happiness=merged[:,-1]
happiness

array(['8', '10', '9', '6', '7', '8', '9', '5', '7'], dtype='<U21')

### Task 3: Sort Scores

**Scenario:** HR needs to identify the range of happiness scores to plan specific interventions.

**Action:** Sort and print the happiness scores in ascending order.

In [12]:
# write code here
happiness=happiness.astype(float)
happiness


array([ 8., 10.,  9.,  6.,  7.,  8.,  9.,  5.,  7.])

In [14]:
happiness.sort()
happiness

array([ 5.,  6.,  7.,  7.,  8.,  8.,  9.,  9., 10.])

### Task 4: Employee Details

**Scenario:** For a meeting, HR needs a list of employees' IDs and departments without other details.

**Action:** Iterate through the array and print each employee's ID and department.

In [17]:
# write code here

id_dept=merged[:,:2]
id_dept

array([['101', 'Sales'],
       ['102', 'HR'],
       ['103', 'IT'],
       ['104', 'Sales'],
       ['105', 'IT'],
       ['106', 'HR'],
       ['107', 'IT'],
       ['108', 'Sales'],
       ['109', 'HR']], dtype='<U21')

### Task 5: Happiness Scores

**Scenario:** HR wants to review individual happiness scores to follow up with specific departments or employees.

**Action:** Print the happiness score alongside each employee ID from the merged array.

In [18]:
# write code here
id_happiness=merged[:,3:]
id_happiness

array([['101', '8'],
       ['102', '10'],
       ['103', '9'],
       ['104', '6'],
       ['105', '7'],
       ['106', '8'],
       ['107', '9'],
       ['108', '5'],
       ['109', '7']], dtype='<U21')

### Task 6: Convert Scores

**Scenario:** For statistical analysis, the HR team needs the happiness scores in a consistent format.

**Action:** Convert the happiness scores to float type using ```astype(float)```.

In [19]:
# write code here
happy=id_happiness[:,1].astype(float)
happy

array([ 8., 10.,  9.,  6.,  7.,  8.,  9.,  5.,  7.])

### Task 7: Average Score

**Scenario:** To measure the effectiveness of current policies, HR needs the average happiness score.

**Action:** Calculate and print the average happiness score of all employees.

In [20]:
# write code here
avg_happiness=np.average(happy)
avg_happiness

np.float64(7.666666666666667)

### Task 8: Unique Departments

**Scenario:** HR is reviewing which departments are represented in the survey to ensure all are included in future plans.

**Action:** Use ```np.unique``` to find and print all unique departments from the employee details.

In [24]:
# first print departments from all the records
depts=id_dept[:,1]
depts
# write code here


array(['Sales', 'HR', 'IT', 'Sales', 'IT', 'HR', 'IT', 'Sales', 'HR'],
      dtype='<U21')

In [25]:
# now print unique departments
np.unique(depts)
# write code here

array(['HR', 'IT', 'Sales'], dtype='<U21')

### Task 9: HR Happiness

**Scenario:** HR is conducting a self-assessment to understand how their own department perceives company policies.

**Action:** Calculate and print the average happiness score within the HR department.

In [29]:
# First print all the records in HR department
HR=merged[merged[:,1]=="HR"]
# write code here

In [31]:
# Now from these records only print  the happiness score column. Convert that to float using astype(float) function
hr_happiness=HR[:,-1].astype(float)
hr_happiness
# write code here

array([10.,  8.,  7.])

In [33]:
# Take an average of this column using np.mean() function
np.average(hr_happiness)
# write code here

np.float64(8.333333333333334)