In [1]:
import numpy as np

In [2]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [3]:
arr[0]

array([1, 2, 3, 4, 5])

In [9]:
#print a column
arr[0,0]

np.int64(1)

In [10]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [11]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])