In [1]:
import numpy as np

Valid sudoku

In [2]:
s=np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3], 
    [4,2,6,8,5,3,7,9,1], 
    [7,1,3,9,2,4,8,5,6], 

    [9,6,1,5,3,7,2,8,4], 
    [2,8,7,4,1,9,6,3,5], 
    [3,4,5,2,8,6,1,7,9]
])

General Question

In [63]:
#Columns : [Age, Math marks, Science Marks]
data=np.array([
    [18,85,78], #student 1
    [19,92,88], #student 2
    [17,76,95], #student 3
    [18,65,70], #student 4
    [20,90,85]  #student 5
])

In [36]:
data.shape

(5, 3)

In [37]:
#Find the average age of students
age=data[0:,0]
age

array([18, 19, 17, 18, 20])

In [38]:
age.mean()

np.float64(18.4)

In [39]:
#Extract maths marks of all stuents
math=data[0:,1]
math

array([85, 92, 76, 65, 90])

In [40]:
#Find the highest science mark 
sci = data[0:,-1]

sci

array([78, 88, 95, 70, 85])

In [41]:
sci.max()

np.int64(95)

In [42]:
np.max(data[:,2])

np.int64(95)

In [43]:
#Get the details of students who got more than 90 in maths
data[:,1]>90


array([False,  True, False, False, False])

In [44]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [64]:
#Increase the math marks of all students by 5
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [48]:
#Find how many students are younger than 19
data[data[:,0]<19]

array([[18, 90, 78],
       [17, 81, 95],
       [18, 70, 70]])

In [50]:
#Calculate the average marks in each subject (clomn wise mean)
avg=np.array([np.mean(data[:,1]),np.mean(data[:,2])])
avg

array([86.6, 83.2])

In [53]:
 np.mean(data[:,1:],axis=0) #axis=0 means col wise and 1 is for row wise

array([86.6, 83.2])

In [57]:
#Get data of students who got at least 80 in both subjects
data[(data[:,1] & data[:,2])>=80]

array([[17, 81, 95],
       [20, 95, 85]])

In [60]:
#Replace all science marks < 75 with 0
data[:,2]<75.replace(0)

SyntaxError: invalid decimal literal (3635248518.py, line 2)

In [62]:
data[data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [ 0,  0,  0],
       [20, 95, 85]])

In [69]:
data[:,2][data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])