In [1]:
import numpy as np

Array creation

In [2]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a=[1,2,3.5,'hello']
a

[1, 2, 3.5, 'hello']

In [4]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [5]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generation
    #np.arange(start,end,step)

In [6]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [9]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [11]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [12]:
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [13]:
arr=np.linspace(1,5,4)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

Random generation function

In [14]:
np.random.rand(5)

array([0.86143517, 0.5923522 , 0.38118761, 0.08856921, 0.97232346])